package de.rehatech.homeekt.const

enum class NodeState(val id: Float) {
    NONE(0F),
    AVAILABLE(1F),
    UNAVAILABLE(2F),
    UPDATE_IN_PROGRESS(3F),
    WAITING_FOR_ATTRIBUTES(4F),
    INITIALIZING(5F),
    USER_INTERACTION_REQUIRED(6F),
    PASSWORD_REQUIRED(7F),
    HOST_UNAVAILABLE(8F),
    DELETE_IN_PROGRESS(9F),
    COSI_CONNECTED(10F),
    BLOCKED(11F),
    WAITING_FOR_WAKEUP(12F),
    REMOTE_NODE_DELETED(13F)
}